version: "3"
services:
    web:
        image: "deftnt/asp_net_core_sql_server"
        ports:
            - "8080:80"
        restart: always
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        hostname: 'sqlserver'
        environment:
            SA_PASSWORD: "ThisIsPass1@"
            ACCEPT_EULA: "Y"
        restart: always